import ogImageSrc from "@images/social.png";

export const SITE = {
  title: "Sinergia Valores S.A",
  tagline: "El puente hacia tu nuevo hogar Sinergia Valores.",
  description:
    "Garantiza tu futuro hogar en segundos - Solicita una fianza con nosotros.",
  description_short: "Garantiza tu futuro hogar en segundos.",
  url: "https://screwfast.uk",
  author: "Justo Becerra",
};

export const SEO = {
  title: SITE.title,
  description: SITE.description,
  structuredData: {
    "@context": "https://schema.org",
    "@type": "WebPage",
    inLanguage: "en-US",
    "@id": SITE.url,
    url: SITE.url,
    name: SITE.title,
    description: SITE.description,
    isPartOf: {
      "@type": "WebSite",
      url: SITE.url,
      name: SITE.title,
      description: SITE.description,
    },
  },
};

export const ArrepentimientoFormInfo = {
  title: "Arrepentimiento",
  description:
    "Solicitar la revocación de un producto o servicio contratado con Sinergia Valores S.A. dentro de los 10 (diez) días corridos contados a partir de la fecha de recibido el contrato o de la disponibilidad efectiva del producto o servicio, lo que suceda último; de esta manera, podrás arrepentirte y deshacer la contratación del producto/servicio solicitado en ese plazo informado.",
  name: "Nombre Completo",
  // lastname: "Apellido",
  nacionality: "Nacionalidad",
  idnumber: "Documento y Numero",
  phonenumber: "Telefono/Celular de contacto",
  mail: "Mail",
  serviceorproduct: "Servicio o Producto",
  sendtext: "Enviar",
};

export const questionsFrecuentes = [
  {
    question: "¿QUIENES SOMOS?",
    answer:
      "GRUPO DE PROFESIONALES MULTIDISCIPLINARIOS DEL RAMO LEGAL Y CONTABLE DEDICADOS A LA GESTIÓN DE SERVICIOS FINANCIEROS.",
  },
  {
    question: "¿QUE ES LA FIANZA PARA ALQUILER DE SINERGIA VALORES S.A.?",
    answer:
      "¿QUE ES LA FIANZA PARA ALQUILER DE SINERGIA VALORES S.A.? ES UN AVAL NO PROPIETARIO A PARTIR DE UN EXHAUSTIVO ANÁLISIS CREDITICIO SOBRE EL POTENCIAL INQUILINO. EN CASO DE INCUMPLIMIENTO, A DIFERENCIA DE LAS GARANTÍAS PROPIETARIAS TRADICIONALES, SINERGIA VALORES S.A. CUBRE LAS OBLIGACIONES PENDIENTES Y LLEVA ADELANTE SIN COSTOS PARA EL PROPIETARIO TODAS LAS ACCIONES JUDICIALES Y EXTRAJUDICIALES NECESARIAS HASTA LA RESTITUCIÓN DEL INMUEBLE.",
  },
  {
    question:
      "¿QUE DOCUMENTACIÓN ES NECESARIA PARA APLICAR EN EL SISTEMA DE FIANZAS PARA ALQUILER DE SINERGIA VALORES S.A.?",
    answer:
      "EN LA OPCIÓN DE REQUISITOS SE ENCUENTRA LA DOCUMENTACIÓN NECESARIA PARA EMPLEADOS, MONOTRIBUTISTAS, RESPONSABLES INSCRIPTOS PERSONA FÍSICA Y PERSONAS JURÍDICAS. (VÍNCULO REQUISITOS)",
  },
  {
    question: "¿QUE ES UN CO-GARANTE?",
    answer:
      "ES UNA PERSONA SELECCIONADA POR EL INQUILINO QUE AYUDA A CALIFICAR Y APLICAR PARA LA FIANZA DE SINERGIA VALORES S.A. DEBE TENER INGRESOS DEMOSTRABLES Y FIRMA JUNTO CON EL INQUILINO. NO ES NECESARIO QUE VIVAN EN LA PROPIEDAD.",
  },
  {
    question: "¿CUANDO SE ABONA LA FIANZA?",
    answer:
      "SE ABONA CUANDO ESTE TODO LISTO PARA FIRMARSE EL CONTRATO DE ALQUILER.",
  },
  {
    question:
      "¿QUE SUCEDE SI LA FIANZA ES ABONADA PERO LA OPERACIÓN INMOBILIARIA ES CANCELADA? ",
    answer:
      "SI LA FIANZA FUE ABONADA, PERO LA OPERACIÓN ES CANCELADA, POR NOVENTA DÍAS (90) ES POSIBLE UTILIZAR EL MONTO ABONADO PARA LA FIANZA DE ALQUILER DE OTRA PROPIEDAD Y SE ABONA SOLO LA DIFERENCIA DE LA FIANZA. SI NO SE REALIZA OTRA OPERACIÓN DE ALQUILER, SE PROCEDE A RESTITUIR EL VALOR ABONADO POR EL CLIENTE.",
  },
  {
    question: "¿QUE NECESITO PARA COTIZAR EL SERVICIO?",
    answer:
      "ES POSIBLE MEDIANTE EL COTIZADOR GRATUITO (VINCULO A LA CALCULADORA) TENER UN PRESUPUESTO APROXIMADO.  EL PRESUPUESTO FINAL SE CONCLUYE EN BASE A LOS VALORES REALES DEL CONTRATO DE ALQUILER Y LA DOCUMENTACION REQUERIDA.",
  },
  {
    question: "¿QUE ES Y QUE VENTAJA TIENE EL BUEN CUMPLIMIENTO?",
    answer:
      "SI EL INQUILINO ABONA EN TERMINO TANTO EL ALQUILER COMO LAS EXPENSAS, EL MISMO DISPONDRA DE UN DESCUENTO POR BUEN CUMPLIMIENTO EN LA RENOVACION DEL CONTRATO DE FIANZA PARA SU PROXIMO ALQUILER. EL MISMO ES VALIDO POR SEIS MESES (6), Y EN CASO DE NO UTILIZARLO ES POSIBLE EJECUTARSE SOBRE REFERIDO DE PARTE DEL CLIENTE.",
  },
  {
    question: "¿COMO SE ABONA EL SERVICIO?",
    answer:
      "ALTERNATIVAS DE PAGO DISCRIMINADAS EN LA PAGINA Y OPCIONES DE FINANCIACION A MEDIDA. ES POSIBLE EN EFECTIVO O TRANSFERENCIA.",
  },
  {
    question:
      "¿ES NECESARIO APORTAR INFORMACION DEL INMUEBLE O INMOBILIARIA AL MOMENTO DE PRESUPUESTAR EL SERVICIO?",
    answer:
      "NO, SOLO ES NECESARIO EL VALOR DE ALQUILER Y EXPENSAS, Y DE MANERA GRATUITA ES POSIBLE SABER SI CALIFICA PARA EL SERVICIO.",
  },
  {
    question: "¿CUANTO TIEMPO TARDA EN APROBARSE LA FIANZA?",
    answer:
      "EL INQUILINO TIENE PREAPROBACION INMEDIATA Y EN 24 HS HABILE A APARTIR DE LA RECEPCION DE LA DOCUMENTACION COMPLETA TIENE LA APROBACION FINAL.",
  },
  {
    question: "¿ES POSIBLE COORDINAR UNA REUNION?",
    answer:
      "SI, COORDINAMOS UNA REUNION PRESENCIAL O VIA ZOOM. EN CASO DE SER PRESENCIAL, ES POSIBLE COORDINARLAS EN NUESTRAS OFICINAS.",
  },
  {
    question:
      "¿ES OBLIGATORIO DIRIGIRSE PERSONALMENTE A FIRMAR EL CONTRATO DE FIANZA?",
    answer:
      "NO ES OBLIGATORIO. DISPONEMOS DE 3 PROCEDIMIENTOS DE FIRMA: 1) PROCEDIMIENTO SEMI-PRESENCIAL, CUYA FIRMA ES OLOGRAFA AL MOMENTO DE LA FIRMA DEL CONTRATO DE ALQUILER, 2) PROCEDIMIENTO ONLINE, CUYA FIRMA Y CERTIFICACION ES DIGITAL POR MEDIO DE APLICACIÓN Y 3) PROCEDIMIENTO PRESENCIAL, CUYA FIRMA ES OLOGRAFA EN NUESTRAS OFICINAS.",
  },
  {
    question: "¿COMO SE SI TENGO EL AVAL DE SINERGIA VALORES S.A.?",
    answer: `ES SIMPLE, LE ENVIAMOS AL MAIL DEL PROPIETARIO, INQUILINO E INMOBILIARIA EL AVAL NUESTRO CON FIRMA DIGITAL. 
    LA VALIDEZ DE LA FIRMA DIGITAL ES POSIBLE VERIFICARSE EN 
    <a target="_blank" href="https://www.argentina.gob.ar/jefatura/innovacion-publica/innovacion-administrativa/firma-digital/plataforma-de-firma-digital">Verificación Secretaria de Modernización</a>. 
    PARA MAS INFORMACION REFERIDA A LA FIRMA DIGITAL EN LA REPUBLICA ARGENTINA PODÉS VISITAR EL SITIO DE LA SECRETARIA DE MODERNIZACION DE PRESIDENCIA DE LA NACION. <a target="_blank" href="https://www.argentina.gob.ar/jefatura/innovacion-publica/innovacion-administrativa/firma-digital/plataforma-de-firma-digital">Información Firma Digital</a>.`,
  },
  {
    question:
      "¿COMO SE GESTIONA EL RECLAMO ANTE INCLUMPLIENTO POR PARTE DEL INQUILINO?",
    answer: `SE REALIZA POR MEDIO DE LA PAGINA DE SINERGIA VALORES S.A. (VINCULO PLANILLA POR INCUMPLIMIENTO).`,
  },
  {
    question:
      "¿TIENE EL PROPIETARIO GASTOS JUDICIALES O EXTRAJUDICIALES EN CASO DE INCUMPLIMIENTO?",
    answer: `NO, SINERGIA VALORES S.A. SE HACE CARGO DEL 100% DE LOS GASTOS JUDICIALES Y EXTRAJUDICIALES EN CASO DE INCUMPLIMIENTO.`,
  },
  {
    question: "¿TIENE EL PROPIETARIO GASTOS POR LA GESTION DE LA FIANZA?",
    answer: `NO, EL INQUILINO ABONA EL 100 % DEL GASTO POR LA GESTION DE LA FIANZA.`,
  },
  {
    question:
      "¿QUE COBERTURA Y PLAZO TIENE LA FIANZA DE SINERGIA VALORES S.A.?",
    answer: `LA MISMA CUBRE EL MONTO DE ALQUILER Y EXPENSAS DETALLADOS EN EL CONTRATO DE ALQUILER POR EL CUAL SE GESTIONA LA FIANZA HASTA LA RESTITUCION DEL INMUEBLE. EN EL CASO DE LAS EXPENSAS, COMO PUEDEN TENER UNA VARIACION LA MISMA ES AFIANZADA EN HASTA UN TREINTA POR CIENTO (30%) EN AJUSTE SEMESTRAL QUE PUEDA SUFRIR.`,
  },
  {
    question: "¿ES POSIBLE COORDINAR UNA REUNION?",
    answer: `SI, COORDINAMOS UNA REUNION PRESENCIAL O VIA ZOOM. EN CASO DE SER PRESENCIAL, ES POSIBLE COORDINARLAS EN NUESTRAS OFICINAS.`,
  },
  {
    question:
      "¿COMO SE SI MI FUTURO INQUILINO ESTA AVALADO POR SINERGIA VALORES S.A? ",
    answer: `UNA VEZ VERIFICADO Y CALIFICADO EL INQUILINO, Y EN CASO DE AVANZAR CON LA FIRMA DEL CONTRATO DE ALQUILER, NUESTRO EQUIPO ENVIA POR E-MAIL EL CONTRATO DE FIANZA CON FIRMA DIGITAL DE SINERGIA VALORES S.A. POR AL INQUILINO, PROPIETARIO E INMOBILIARIA. ESTO SE GESTIONA ANTES DE LA FIRMA DEL CONTRATO DE ALQUILER, PARA QUE TODAS LAS PARTES PUEDAN REVISARLAS CON ANTICIPACION.`,
  },
  {
    question:
      "¿COMO PUEDO VERIFICAR SI LA FIANZA QUE RECIBI POR E-MAIL ES VALIDA LEGALMENTE?",
    answer: `EL CONTRATO DE FIANZA EMITIDO POR SINERGIA VALORES S.A ES FIRMADO DIGITALMENTE. LA VALIDEZ DE LA FIRMA DIGITAL ES POSIBLE VERIFICARSE EN Verificación Secretaria de Modernización. PARA MAS INFORMACION REFERIDA A LA FIRMA DIGITAL EN LA REPUBLICA ARGENTINA PODÉS VISITAR EL SITIO DE LA SECRETARIA DE MODERNIZACION DE PRESIDENCIA DE LA NACION. Información Firma Digital.`,
  },
  {
    question:
      "¿QUE VENTAJAS TIENE FORMAR PARTE DE LA RED DE INMOBILIARIAS ADHERIDAS DE SINERGIA VALORES S.A.?",
    answer: `EN PRIMERO LUGAR, LOS INMUEBLES EN ALQUILER SON PUBLICADOS EN NUESTRA PAGINA Y REDES SOCIALES. EN SEGUNDO LUGAR, ESTAMOS PRESENTES POR MEDIOS PUBLICITARIOS, Y FORMARIAN PARTE DE NUESTROS ANUNCIOS. POR ULTIMO, LA INMOBILIARIA QUE SE ADHIERA AL SISTEMA DE FIANZAS DE SINERGIA VALORES S.A, FORMA PARTE DEL SISTEMA DE COMISIONES POR VOLUMEN DE CONTRATOS CONCERTADOS.`,
  },
  {
    question:
      "¿QUE VENTAJAS TIENE EL SISTEMA DE FIANZAS DE SINERGIA VALORES S.A.?",
    answer: `LOS INQUILINOS SON ANALIZADOS DE MANERA EXHAUSTIVA EN MATERIA FINANCIERA Y DE HISTORIAL CREDITICIO, POR LO QUE TIENEN RECORD FINANCIERO OPTIMO. A SU VEZ SINERGIA VALORES S.A. PROVEE LIQUIDEZ INMEDIATA EN CASO INCUMPLIMIENTOS POR PARTE DEL INQUILINO HASTA LA RESTITUCION DEL BIEN. EL EQUIPO DE SINERGIA VALORES S.A. SE HACE CARGO DE EL PROCEDIMIENTO SIN GASTOS PARA LA INMOBILIARIA NI PROPIETARIO`,
  },
  {
    question: "¿ES POSIBLE COORDINAR UNA REUNION?",
    answer: `SI, COORDINAMOS UNA REUNION PRESENCIAL O VIA ZOOM. EN CASO DE SER PRESENCIAL, ES POSIBLE COORDINARLAS EN LA INMOBILIARIA O EN NUESTRAS OFICINAS.`,
  },
  {
    question: "¿SE UTILIZA EL MISMO MODELO DE CONTRATO DE ALQUILER?",
    answer: `SI, EL EQUIPO DE SIENRGIA VALORES S.A. SE COMUNICA CON LA INMOBILIARIA PARA AGILIZAR EL PROCEDIMIENTO A PARTIR DE UNA CLAUSUAL ANEXO, LA CUAL FORMA PARTE DEL CONTRATO DE FIANZA Y SE INCORPORA AL CONTRATO DE ALQUILER.`,
  },
  {
    question: "¿QUE CANALES DE COMUNICACIÓN TENEMOS ANTE UNA CONSULTA TECNICA?",
    answer: `CONTAMOS CON CANALES DE COMUNICACIÓN VIA TELEFONICA, MAIL INSTITUCIONAL, PAGINA WEB Y OFICINAS.`,
  },
  {
    question:
      "¿COMO PUEDO VERIFICAR SI LA FIANZA QUE RECIBI POR E-MAIL ES VALIDA LEGALMENTE?",
    answer: `EL CONTRATO DE FIANZA EMITIDO POR SINERGIA VALORES S.A ES FIRMADO DIGITALMENTE. LA VALIDEZ DE LA FIRMA DIGITAL ES POSIBLE VERIFICARSE EN Verificación Secretaria de Modernización. PARA MAS INFORMACION REFERIDA A LA FIRMA DIGITAL EN LA REPUBLICA ARGENTINA PODÉS VISITAR EL SITIO DE LA SECRETARIA DE MODERNIZACION DE PRESIDENCIA DE LA NACION. Información Firma Digital.`,
  },
  {
    question:
      "¿DEBO COORDINAR LA FIRMA DEL CONTRATO DE LOCACION CON SINERGIA VALORES S.A.?",
    answer: `NO, SIGUE SIENDO COORDINADO POR LA INMOBILIARIA A SU CRITERIO Y EN BENEFICIO DE LA MEJOR ATENCION DE SUS CLIENTES.`,
  },
];

export const OG = {
  locale: "en_US",
  type: "website",
  url: SITE.url,
  title: `${SITE.title}`,
  description:
    "Sinergia Valores Sistema de fianzas de alquiler 100 % digital con calificacion en 24 hs.",
  image: ogImageSrc,
};
